credentials:
  system:
    domainCredentials:
      - credentials:
        - gitHubApp:
            appID: "${GITHUB_APP_ID}"
            description: "GitHub app"
            id: "${GITHUB_APP_ID}"
            privateKey: "${GITHUB_APP_KEY}"

# ref https://www.roger.ml/p/jenkins-ci-github-app-authentication